@smoke
Feature:Creation
Scenario: Complete Form
Then Login
Then Navigate to"Setting"
Then click"Dynamic Form"
Then Reach"Page Master"
Then Click"icon-settings dropbtn"
Then click"dropdown-item"
Then select"Select Field Type"
Then select"Select Element"
Then Click"chk_popup"
Then Enter"txt_btn_name"
Then select"ddlbtniconforforms"
Then click"btnsavepageform"
Then Click"swal-button swal-button--confirm"
Then click"btn-close btn_MappingPage_close"
Then click1"dropdown-item"
Then click"TablePageID(this)"
Then Enter"id="txt_TableName"
Then select"ddlIsEdit"
Then select"ddlIsDelete"
Then enter"txtDeleteConfirmation"
Then select"ddlIsinfoicon"
Then select"ddlIssummaryicon"
Then select"ddlIsFeedBack"
Then click"chk_workflow"
Then click"chk_Table"
Then click"SaveTabledetails"
Then click1"class="swal-button swal-button--confirm"
Then click"Add"
Then select"ddltableScreenname"
Then select"ddlScreenformlst"
Then select"ddlfieldtype"
Then select"chk_isPrimary"
Then select"ddltableScreenformctrls"
Then Enter"txt_width"
Then clickmappingsave"SaveColumndetails"
Then click2"class="swal-button swal-button--confirm"
Then click"pageroleclose"
Then click"btn-close"
Then click2""icon-settings dropbtn"
Then click1"ScreenLayout(this)"
Then select"ddlcontentper"
Then select"ddlcontMap"
Then click"multiselect-selected-text"
Then select"Super Admin"
Then click"10"
Then click"btnscreenlayoutsave"
Then click3"class="swal-button swal-button--confirm"
Then select1"ddlcontentper"
Then select1"ddlcontMap"
Then click1"multiselect-selected-text"
Then select1"Super Admin"
Then clicka"10"
Then click1"btnscreenlayoutsave"
Then click4"class="swal-button swal-button--confirm"
Then click_manange_screen_layout"btn-close"
Then Goto"ASample Technical Publication"
Then click"Sample Work Assignmnt"
Then check created Add Work task Button is dispalyed perfectly"Add"